#!/bin/bash

function success() {
  echo "ok"
}

function failure() {
  echo "FAILED ($@)"
  exit 1
}

if [ "$(git rev-parse --abbrev-ref HEAD)" == "master" ]; then
  git reset --hard HEAD 1>/dev/null 2>&1
  git pull -f 1>/dev/null 2>&1
fi

echo "Checking Requirements:"

echo -n "docker is running       .. " 
[ "$(docker info --format '{{ .ServerErrors }}')" == "[]" ] && success || failure "is docker running?"

echo -n "docker v19+             .. "
[ "$(docker info --format '{{ .ServerVersion }}' | cut -d. -f1)" -ge 19 ] && success || failure "should be 19+"

echo -n "docker-compose v1.25+   .. "
DOCKER_COMPOSE_VERSION=$(docker-compose --version | sed -E 's/.*([0-9]{1,2}.[0-9]{2}.[0-9]+),.*/\1/' | cut -d. -f2)
[ "${DOCKER_COMPOSE_VERSION:-0}" -ge 25 ] && success || failure "should be 1.25+" 

echo

stackFile=$(mktemp --version 2>/dev/null | grep GNU >/dev/null && mktemp --suffix .playpit-labs.${1} || mktemp)
curl -s -o ${stackFile:-/tmp/.playpit-labs.${1}} https://playpit-labs-assets.s3-eu-west-1.amazonaws.com/docker-compose/sbeliakou-${1}.yml --fail || {
  echo -e "Error: can't find requested training\n"
  echo -e 'Usage:\n  ./start <training_name>\n\nAvailable trainings:\n  kubernetes\n  docker\n'
  exit 1
}

echo Cleaning up:
docker ps -qa --filter label=lab | xargs $(xargs --version 2>/dev/null | grep GNU >/dev/null && echo "-r") docker rm -f
docker volume ls --filter label=lab -q | xargs $(xargs --version 2>/dev/null | grep GNU >/dev/null && echo "-r") docker volume rm -f
docker network ls --filter label=lab -q | xargs $(xargs --version 2>/dev/null | grep GNU >/dev/null && echo "-r") docker network rm

echo -e "\nPulling updates:"
PWD=$PWD docker-compose -f ${stackFile} pull

echo -e "\nStarting New Stack:"
PWD=$PWD PAYPIT_LL="${PLAYPIT_LL:-}" PLAYPIT_NAME="${PLAYPIT_NAME:-}" docker-compose -f ${stackFile} up -d --renew-anon-volumes --remove-orphans
rm -f $stackFile

## Finish
echo -e "\nReady! Browse: http://lab.playpit.net:8081\n"